-- Thêm các cột mới cho bảng DETHI và BAITHI

USE HeThongBanTayVang;
GO

-- DETHI: ChecksumData, NguoiCapNhat, NgayCapNhat
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DETHI' AND COLUMN_NAME = 'ChecksumData')
BEGIN
    ALTER TABLE DETHI ADD ChecksumData nvarchar(500) NULL;
    PRINT 'ChecksumData column added to DETHI';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DETHI' AND COLUMN_NAME = 'NguoiCapNhat')
BEGIN
    ALTER TABLE DETHI ADD NguoiCapNhat int NULL;
    PRINT 'NguoiCapNhat column added to DETHI';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DETHI' AND COLUMN_NAME = 'NgayCapNhat')
BEGIN
    ALTER TABLE DETHI ADD NgayCapNhat datetime2 NULL;
    PRINT 'NgayCapNhat column added to DETHI';
END
GO

-- BAITHI: ThoiGianBatDau, NgayCapNhat, LyDoKetThuc
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BAITHI' AND COLUMN_NAME = 'ThoiGianBatDau')
BEGIN
    ALTER TABLE BAITHI ADD ThoiGianBatDau datetime2 NULL;
    PRINT 'ThoiGianBatDau column added to BAITHI';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BAITHI' AND COLUMN_NAME = 'NgayCapNhat')
BEGIN
    ALTER TABLE BAITHI ADD NgayCapNhat datetime2 NULL;
    PRINT 'NgayCapNhat column added to BAITHI';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'BAITHI' AND COLUMN_NAME = 'LyDoKetThuc')
BEGIN
    ALTER TABLE BAITHI ADD LyDoKetThuc nvarchar(255) NULL;
    PRINT 'LyDoKetThuc column added to BAITHI';
END
GO

-- CANHBAOGIANLAN: MucDoNghiemTrong, CorrelationId
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CANHBAOGIANLAN' AND COLUMN_NAME = 'MucDoNghiemTrong')
BEGIN
    ALTER TABLE CANHBAOGIANLAN ADD MucDoNghiemTrong nvarchar(50) NULL;
    PRINT 'MucDoNghiemTrong column added to CANHBAOGIANLAN';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CANHBAOGIANLAN' AND COLUMN_NAME = 'CorrelationId')
BEGIN
    ALTER TABLE CANHBAOGIANLAN ADD CorrelationId nvarchar(100) NULL;
    PRINT 'CorrelationId column added to CANHBAOGIANLAN';
END
GO

PRINT 'Migration 003 completed successfully!';

-- Verify
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DETHI' 
ORDER BY ORDINAL_POSITION;