CREATE TABLE [DANG_KY_THI] (
    [Id] INT IDENTITY(1,1) NOT NULL,
    [HoTen] NVARCHAR(255) NOT NULL,
    [Cccd] NVARCHAR(20) NOT NULL,
    [SoDienThoai] NVARCHAR(20) NOT NULL,
    [Email] NVARCHAR(255) NULL,
    [MatKhauHash] NVARCHAR(255) NOT NULL,
    [DonViCongTac] NVARCHAR(255) NULL,
    [ChuyenNganh] NVARCHAR(255) NULL,
    [KhoaPhongId] INT NULL,
    [MucDichThi] NVARCHAR(255) NULL,
    [TrangThai] NVARCHAR(50) NOT NULL DEFAULT 'Pending',
    [NgayDangKy] DATETIME NOT NULL DEFAULT GETDATE(),
    [GhiChu] NVARCHAR(1000) NULL,
    [NguoiDuyetId] INT NULL,
    [NgayDuyet] DATETIME NULL,
    CONSTRAINT [PK_DANG_KY_THI] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DANG_KY_THI_KhoaPhong] FOREIGN KEY ([KhoaPhongId]) REFERENCES [KHOA_PHONG] ([Id])
);
GO
