// <auto-generated />
using System;
using BanTayVang.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BanTayVang.API.Migrations
{
    [DbContext(typeof(BanTayVangDbContext))]
    [Migration("20260715013112_AddEnglishColumnNames")]
    partial class AddEnglishColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BanTayVang.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DiaChi_IP");

                    b.Property<string>("DuongDan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExamSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiThaoTac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaHttp")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__LOGTHAOT__3214EC076B8FE2F7");

                    b.HasIndex("ExamSubmissionId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BanTayVang.API.Models.CheatWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionTime")
                        .HasColumnType("datetime");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExamSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiCanhBao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MucDoNghiemTrong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLanViPham")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CANHBAOG__3214EC07EB40AF3B");

                    b.HasIndex("ExamSubmissionId");

                    b.ToTable("CheatWarnings");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DeptManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DeptManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CustomStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ExamId", "UserId")
                        .IsUnique();

                    b.ToTable("ExamAssignments");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MinPassQuestions")
                        .HasColumnType("int");

                    b.Property<string>("OrganizedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ExamCampaigns");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamPaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecksumData")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ExamPaperCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExamPaperName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsResultPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("KyThiId")
                        .HasColumnType("int");

                    b.Property<string>("LinkTruyCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinPassQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiCongBo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ThoiGianCongBo")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DETHI__3214EC07A61E2A85");

                    b.HasIndex("KyThiId");

                    b.ToTable("ExamPapers");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamPaperQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExamPaperId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<double?>("TrongSo")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK__DETHI_CA__3214EC074EED9C55");

                    b.HasIndex("ExamPaperId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ExamPaperQuestions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChuyenNganh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("DonViCongTac")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MucDichThi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ExamRegistrations");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CongBoRieng")
                        .HasColumnType("bit");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<string>("DanhGiaKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExamCampaignId")
                        .HasColumnType("int");

                    b.Property<string>("ExamPaperCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ExamPaperId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiCongBoRieng")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianCongBoRieng")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TongSoCanhBao")
                        .HasColumnType("int");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<double?>("TotalScore")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BAITHI__3214EC077508193A");

                    b.HasIndex("ExamCampaignId");

                    b.HasIndex("ExamPaperId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamSubmissions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelatedUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Phiendangnhap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP");

                    b.Property<string>("ThietBiUserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianHetHan")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__PHIENDAN__3214EC0786D0DC9F");

                    b.HasIndex("UserId");

                    b.ToTable("Phiendangnhaps");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CAUHOI__3214EC070C9BF858");

                    b.HasIndex("QuestionCategoryId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.QuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__LOAICAUH__3214EC071DD715C9");

                    b.ToTable("QuestionCategories");
                });

            modelBuilder.Entity("BanTayVang.API.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__LUACHON__3214EC07716560A0");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaVaiTro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__VAITRO__3214EC07828E2FD1");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BanTayVang.API.Models.SubmissionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauTraLoiTuLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DaLuu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ExamSubmissionId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<double?>("ScoreObtained")
                        .HasColumnType("float");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianTraLoi")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__CHITIETL__3214EC07199D44E7");

                    b.HasIndex("ExamSubmissionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("SubmissionDetails");
                });

            modelBuilder.Entity("BanTayVang.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DeptManagerDeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TAIKHOAN__3214EC07D2108DB4");

                    b.HasIndex("DeptManagerDeptId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BanTayVang.API.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TAIKHOAN__3214EC07DCEDD2F9");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BanTayVang.API.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.AuditLog", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamSubmission", "IdBaiThiNavigation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ExamSubmissionId")
                        .HasConstraintName("FK__LOGTHAOTA__IdBai__5BE2A6F2");

                    b.HasOne("BanTayVang.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IdBaiThiNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanTayVang.API.Models.CheatWarning", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamSubmission", "IdBaiThiNavigation")
                        .WithMany("CheatWarnings")
                        .HasForeignKey("ExamSubmissionId")
                        .HasConstraintName("FK__CANHBAOGI__IdBai__5441852A");

                    b.Navigation("IdBaiThiNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Department", b =>
                {
                    b.HasOne("BanTayVang.API.Models.User", "DeptManager")
                        .WithMany()
                        .HasForeignKey("DeptManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeptManager");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamAssignment", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamPaper", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanTayVang.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamCampaign", b =>
                {
                    b.HasOne("BanTayVang.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamPaper", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamCampaign", "KyThiNavigation")
                        .WithMany()
                        .HasForeignKey("KyThiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KyThiNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamPaperQuestion", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamPaper", "IdDeThiNavigation")
                        .WithMany("ExamPaperQuestions")
                        .HasForeignKey("ExamPaperId")
                        .HasConstraintName("FK__DETHI_CAU__IdDeT__5AEE82B9");

                    b.HasOne("BanTayVang.API.Models.Question", "IdCauHoiNavigation")
                        .WithMany("ExamPaperQuestions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__DETHI_CAU__IdCau__59FA5E80");

                    b.Navigation("IdCauHoiNavigation");

                    b.Navigation("IdDeThiNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamRegistration", b =>
                {
                    b.HasOne("BanTayVang.API.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamSubmission", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamCampaign", "KyThiNavigation")
                        .WithMany()
                        .HasForeignKey("ExamCampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BanTayVang.API.Models.ExamPaper", "IdDeThiNavigation")
                        .WithMany("ExamSubmissions")
                        .HasForeignKey("ExamPaperId")
                        .HasConstraintName("FK__BAITHI__IdDeThi__52593CB8");

                    b.HasOne("BanTayVang.API.Models.User", "IdTaiKhoanNavigation")
                        .WithMany("ExamSubmissions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__BAITHI__IdTaiKho__534D60F1");

                    b.Navigation("IdDeThiNavigation");

                    b.Navigation("IdTaiKhoanNavigation");

                    b.Navigation("KyThiNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Notification", b =>
                {
                    b.HasOne("BanTayVang.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Phiendangnhap", b =>
                {
                    b.HasOne("BanTayVang.API.Models.User", "IdTaiKhoanNavigation")
                        .WithMany("Phiendangnhaps")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__PHIENDANG__IdTai__5DCAEF64");

                    b.Navigation("IdTaiKhoanNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Question", b =>
                {
                    b.HasOne("BanTayVang.API.Models.QuestionCategory", "IdLoaiCauHoiNavigation")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionCategoryId")
                        .HasConstraintName("FK__CAUHOI__IdLoaiCa__5629CD9C");

                    b.Navigation("IdLoaiCauHoiNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.QuestionOption", b =>
                {
                    b.HasOne("BanTayVang.API.Models.Question", "IdCauHoiNavigation")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__LUACHON__IdCauHo__5CD6CB2B");

                    b.Navigation("IdCauHoiNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.RefreshToken", b =>
                {
                    b.HasOne("BanTayVang.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanTayVang.API.Models.SubmissionDetail", b =>
                {
                    b.HasOne("BanTayVang.API.Models.ExamSubmission", "IdBaiThiNavigation")
                        .WithMany("SubmissionDetails")
                        .HasForeignKey("ExamSubmissionId")
                        .HasConstraintName("FK__CHITIETLA__IdBai__571DF1D5");

                    b.HasOne("BanTayVang.API.Models.Question", "IdCauHoiNavigation")
                        .WithMany("SubmissionDetails")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK__CHITIETLA__IdCau__5812160E");

                    b.HasOne("BanTayVang.API.Models.QuestionOption", "IdLuaChonDaChonNavigation")
                        .WithMany("SubmissionDetails")
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("FK__CHITIETLA__IdLua__59063A47");

                    b.Navigation("IdBaiThiNavigation");

                    b.Navigation("IdCauHoiNavigation");

                    b.Navigation("IdLuaChonDaChonNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.User", b =>
                {
                    b.HasOne("BanTayVang.API.Models.Department", "ManagedDepartment")
                        .WithMany()
                        .HasForeignKey("DeptManagerDeptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ManagedDepartment");
                });

            modelBuilder.Entity("BanTayVang.API.Models.UserRole", b =>
                {
                    b.HasOne("BanTayVang.API.Models.Role", "IdVaiTroNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__TAIKHOAN___IdVai__5FB337D6");

                    b.HasOne("BanTayVang.API.Models.User", "IdTaiKhoanNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__TAIKHOAN___IdTai__5EBF139D");

                    b.Navigation("IdTaiKhoanNavigation");

                    b.Navigation("IdVaiTroNavigation");
                });

            modelBuilder.Entity("BanTayVang.API.Models.UserSession", b =>
                {
                    b.HasOne("BanTayVang.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamPaper", b =>
                {
                    b.Navigation("ExamPaperQuestions");

                    b.Navigation("ExamSubmissions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.ExamSubmission", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CheatWarnings");

                    b.Navigation("SubmissionDetails");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Question", b =>
                {
                    b.Navigation("ExamPaperQuestions");

                    b.Navigation("QuestionOptions");

                    b.Navigation("SubmissionDetails");
                });

            modelBuilder.Entity("BanTayVang.API.Models.QuestionCategory", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("BanTayVang.API.Models.QuestionOption", b =>
                {
                    b.Navigation("SubmissionDetails");
                });

            modelBuilder.Entity("BanTayVang.API.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BanTayVang.API.Models.User", b =>
                {
                    b.Navigation("ExamSubmissions");

                    b.Navigation("Phiendangnhaps");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
